### ISSUE TITLE
Links to NPM

### ISSUE THREAD

**Issue by ryan953** [ekonstantinidis/npm-click#23]
The list of packages should include links to npm and/or github when it's possible so it's easier to find readme, changelogs, and upgrade instructions.

**Comment by ekonstantinidis** [comment]
@ryan953 Sounds good! Will definitely have a further look later today. Thank you for the suggestion!

**Comment by ekonstantinidis** [comment]
This one is now online! :rocket:

**Comment by ryan953** [comment]
:+1:
