### ISSUE TITLE
Able to input your github repo

### ISSUE THREAD

**Issue by huei90** [ekonstantinidis/npm-click#25]
Hi, thanks for this great work!

It's better if 

1. Input github repo name 
2.  `npm click` will do the rest including crawling package.json on the repo and check the dependencies.
3.  output the result 

Then we don't need to copy and paste the `package.json` file

**Comment by rstacruz** [comment]
even better, an `npm` name should be able to do it. it'd be nice to link it through a badge in the readme as well.

**Comment by ekonstantinidis** [comment]
@huei90 That sounds like a great idea but there is already a website that does exactly what you said and it's also open sourced. Here is the link to the [repo](https://github.com/alanshaw/david-www) and here is the link to the [website](https://david-dm.org/).

I think it would be better if we keep it simple - adding such a feature will require Github authentication for private repos etc. I'm closing this one for now and will have a further look in the future to see if it's worth implementing such feature.
