### ISSUE TITLE
Doesn't support the @ or / namespacing?

### ISSUE THREAD

**Issue by crazy4groovy** [ekonstantinidis/npm-click#26]
I have a custom dependency like:
```
"dependencies": {
    "@d2l/brightspace-auth-assertions": "^2.0.0",
```
which is stored in a private repo (artifactory). It seems to break the tool completely.

"Oops! Something is wrong with your package.json. Please try again."

**Comment by ekonstantinidis** [comment]
Now supports for custom dependencies (https://github.com/ekonstantinidis/npm-click/pull/28). Every dependency with a `@` will be ignored avoiding the error `Oops! Something is wrong with your package.json. Please try again.`.
