### ISSUE TITLE
FR: Fetch deps from module name.

### ISSUE THREAD

**Issue by hemanth** [ekonstantinidis/npm-click#29]
Will be useful if we could fetch the module deps from the name, rather than asking for the package.json?

Update: We could make use of https://salty-bayou-6454.herokuapp.com/ itself, right?

//cc @ekonstantinidis

**Comment by ekonstantinidis** [comment]
I think that would be useful but will have to wait until npm's public api is ready? The registry doesn't currently return such information so closing for now..

**Comment by hemanth** [comment]
:+1:
